language: python
sudo: false
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - pypy
install:
    - python bootstrap.py --setuptools-version=28.0.0
    - bin/buildout -n
script:
    - bin/test-ztk
notifications:
    email: false
cache:
  pip: true
  directories:
    - eggs/
