# Loosely based on:
# https://github.com/zopefoundation/meta/tree/master/config/pure-python
name: tests

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        config:
        # [Python version, extra dependencies]
        - ["2.7",      "setuptools==44.0.0"]
        - ["3.6",      "'setuptools < 52'"]
        - ["3.7",      "'setuptools < 52'"]
        - ["3.8",      "'setuptools < 52'"]
        - ["3.9",      "'setuptools < 52'"]
        - ["pypy-2.7", "setuptools==44.0.0"]
        - ["pypy-3.6", "'setuptools < 52'"]

    runs-on: ubuntu-latest
    name: ${{ matrix.config[0] }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.config[0] }}
    - name: Install library dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libxml2-dev libxslt1-dev
    - name: Cache Python wheels and eggs
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pip
          eggs
        key: ${{ runner.os }}-py-${{ matrix.config[0] }}-${{ hashFiles('buildout.cfg') }}
        restore-keys: |
          ${{ runner.os }}-py-${{ matrix.config[0] }}-
          ${{ runner.os }}-py-
    - name: Install dependencies
      run: |
        python -m pip install -U pip
        pip install -U ${{ matrix.config[1] }} wheel six==$(awk '$1 == "six" {print $3}' ztk-versions.cfg) zc.buildout==$(awk '$1 == "zc.buildout" {print $3}' ztk-versions.cfg) tox
        buildout -n
    - name: Test
      run: bin/test-ztk
      # https://foss.heptapod.net/pypy/pypy/-/issues/3378 breaks zope.password
      # on PyPy3, so ignore failures there for now.
      continue-on-error: ${{ matrix.config[0] == 'pypy-3.6' }}
